# Dynamically generated Kitty colors

background            #131413
foreground            #e8eae8
cursor                #b4d8b4
cursor_text_color     #131413
selection_background  #b4d8b4
selection_foreground  #e8eae8
color0                #0a0a0a
color8                #222322
color1                #d8b4b4
color9                #d8b4b4
color2                #aed1ae
color10               #aed1ae
color3                #e0dcbb
color11               #e0dcbb
color4                #b4bed8
color12               #b4bed8
color5                #c5aed1
color13               #c5aed1
color6                #aed1c6
color14               #aed1c6
color7                #c9ccc9
color15               #e8eae8
active_border_color   #b4d8b4
inactive_border_color #222322
