# Dynamically generated Kitty colors

background            #111114
foreground            #e1deea
cursor                #2900d8
cursor_text_color     #111114
selection_background  #2900d8
selection_foreground  #e1deea
color0                #09090a
color8                #1d1c23
color1                #d80000
color9                #d80000
color2                #04d100
color10               #04d100
color3                #e0c900
color11               #e0c900
color4                #003cd8
color12               #003cd8
color5                #8e00d1
color13               #8e00d1
color6                #00d192
color14               #00d192
color7                #bebbcc
color15               #e1deea
active_border_color   #2900d8
inactive_border_color #1d1c23
