-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = false,
    },
    decoration = {
        active_opacity = 0.85,
        blur = {
            noise = 0.013,
            passes = 4,
            size = 3,
            special = true,
        },
        fullscreen_opacity = 0.95,
        inactive_opacity = 1.0,
        rounding = 10,
        rounding_power = 2.5,
    },
    general = {
        border_size = 1,
        gaps_in = 1,
        gaps_out = 3,
        resize_on_border = false,
    },
})
