layerrule = blur, waybar
layerrule = ignorealpha 0.1, waybar

layerrule = blur, rofi
layerrule = ignorealpha 0.1, rofi

layerrule = blur, swaync-control-center
layerrule = ignorealpha 0.1, swaync-control-center

layerrule = blur, swaync-notification-window
layerrule = ignorealpha 0.1, swaync-notification-window
