#!/usr/bin/env bash
#
# Adjust default device volume and send a notification with the current level
#
# Requires libpulse (pactl)
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    September 07, 2025
# License: MIT

DEF_VALUE=1
MIN=0
MAX=100

usage() {
	local script=${0##*/}

	cat <<- EOF
		USAGE: $script {input|output} {mute|raise|lower} [value]

		Adjust default device volume and send a notification with the current level

		DEVICE:
		  input            Use "@DEFAULT_SOURCE@" (microphone)
		  output           Use "@DEFAULT_SINK@" (speaker/headphones)

		OPTIONS:
		  mute             Toggle device mute
		  raise [value]    Raise volume by [value] (default: $DEF_VALUE)
		  lower [value]    Lower volume by [value] (default: $DEF_VALUE)

		EXAMPLES:
		  Toggle microphone mute:
		    $ $script input mute

		  Raise speaker volume:
		    $ $script output raise

		  Lower speaker volume by 5:
		    $ $script output lower 5
	EOF
}

pactl() {
	command pactl "$1" "$DEV_DEF" "${@:2}"
}

get_state() {
	local state
	state=$(pactl "get-$DEV_STATE" | awk '{print $2}')

	case $state in
		yes) printf "Muted" ;;
		no)  printf "Unmuted" ;;
	esac
}

get_volume() {
	pactl "get-$DEV_VOLUME" | awk '{print $5}' | tr -d '%'
}

get_icon() {
	local state level

	state=$(get_state)
	level=$(get_volume)

	local icon
	local new_level=${1:-$level}

	if [[ $state == Muted ]]; then
		icon="$DEV_ICON-muted"
	else
		if ((new_level < MAX * 33 / 100)); then
			icon="$DEV_ICON-low"
		elif ((new_level < MAX * 66 / 100)); then
			icon="$DEV_ICON-medium"
		else
			icon="$DEV_ICON-high"
		fi
	fi

	printf "%s" "$icon"
}

set_state() {
	if [ "$DEVICE" = "input" ]; then
		swayosd-client --input-volume mute-toggle
	else
		swayosd-client --output-volume mute-toggle
	fi
}

set_volume() {
	local sign
	case $ACTION in
		raise) sign="+" ;;
		lower) sign="-" ;;
	esac

	if [ "$DEVICE" = "input" ]; then
		swayosd-client --input-volume "$sign$VALUE"
	else
		swayosd-client --output-volume "$sign$VALUE"
	fi
}

main() {
	DEVICE=$1
	ACTION=$2
	VALUE=${3:-$DEF_VALUE}

	if ((VALUE < 1)); then
		usage >&2
		return 1
	fi

	case $DEVICE in
		input)
			DEV_DEF="@DEFAULT_SOURCE@"
			DEV_STATE="source-mute"
			DEV_VOLUME="source-volume"
			DEV_ICON="mic-volume"
			DEV_NAME="Microphone"
			;;
		output)
			DEV_DEF="@DEFAULT_SINK@"
			DEV_STATE="sink-mute"
			DEV_VOLUME="sink-volume"
			DEV_ICON="audio-volume"
			DEV_NAME="Volume"
			;;
		*)
			usage >&2
			return 1
			;;
	esac

	case $ACTION in
		mute)
			set_state
			;;
		raise | lower)
			set_volume
			;;
		*)
			usage >&2
			return 1
			;;
	esac
}

main "$@"
